// Code generated by "stringer -type=Type -trimprefix Type"; DO NOT EDIT.

package bipf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeString-0]
	_ = x[TypeBuffer-1]
	_ = x[TypeInt32-2]
	_ = x[TypeDouble-3]
	_ = x[TypeArray-4]
	_ = x[TypeObject-5]
	_ = x[TypeBool-6]
	_ = x[TypeReserved-7]
}

const _Type_name = "StringBufferInt32DoubleArrayObjectBoolReserved"

var _Type_index = [...]uint8{0, 6, 12, 17, 23, 28, 34, 38, 46}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
